### ISSUE TITLE
Hash method changeable?

### ISSUE THREAD

**Issue by jmhmd** [chafey/dicom2ion-js#1]
Is there a chance the hashing algorithm could change in the future to something other than sha256? Using `sha256` as the key for the hash might make it hard to change later - does it make sense to specify the hash algorithm in say the `options` object, and just use `hash` as the key for different file/data hashes? For example:
```js
options: {
    maximumInlineDataLength: 256,
    hashMethod: "sha256"
    dataDictionary: {
      description: "Unknown edition",
      hash: "c2e30d6191b63d67a9a0606da204e00968286bfe1f94c2ccd2dcf9b8d33ebf4b"
    }
  },
  fileInfo: {
    hash: "dc3ff8e550c833236bbee92d163762698b7b0b7b68a1af1b060243580741b7a6",
    createdAt: 2021-02-03T21:22:54.051Z
  },
...
```

**Comment by chafey** [comment]
Yes - this is needed.  I spoke with the IPLD folks yesterday and they are interested in adding support for ION.  Once this is done, we can leverage IPLD Content Identifiers (CIDs) to achieve this.  CIDs contain the codec, hash algorithm and hash digest all in one:

https://github.com/multiformats/cid

**Comment by jmhmd** [comment]
That makes sense, the CID format seems pretty future-proof.
